# Change these first
owner: Asbury-Theological-Seminary-A-Team # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: AsburySeminary.edu
    url: http://www.asburyseminary.edu/
  - name: Zoom
    url: https://asburyseminary.zoom.us/
  - name: Authentication/Single Sign On Systems
    url: https://login.asburyseminary.edu/
  - name: Help Desk
    url: https://helpdesk.asburyseminary.edu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ATS System Status
  introTitle: "Uptime monitor and status page for Asbury Theological Seminary LITS Systems"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Help Desk
      href: https://helpdesk.asburyseminary.edu

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
